version: "3"
services:
  frontend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
  
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "40000:80"

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app

  postgresql:
    build: ./postgresql
    restart: unless-stopped
    container_name: app_postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/sqls/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"